### ISSUE TITLE
TypeError: undefined is not a function in obj.hasOwnProperty(k)

### ISSUE THREAD

**Issue by aaronjensen** [rollbar/rollbar.js#290]
querystring objects seem to break rollbar. It may have something to do with https://github.com/nodejs/node/pull/6289

This is the property that is being scrubbed that is causing the failure:

```
  GET: { color: '999' },
```

Exception: 

```
/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:129
      if (obj.hasOwnProperty(k)) {
              ^

TypeError: undefined is not a function
    at traverse (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:129:15)
    at scrubber (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:431:16)
    at traverse (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:142:14)
    at scrubber (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:431:16)
    at traverse (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:142:14)
    at Object.scrub (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/utility.js:439:3)
    at Array.scrubPayload (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/server/transforms.js:137:5)
    at cb (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/notifier.js:109:31)
    at Array.addRequestData (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/server/transforms.js:129:3)
    at cb (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/notifier.js:109:31)
    at cb (/Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/server/transforms.js:78:5)
    at /Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/node_modules/async/lib/async.js:49:16
    at /Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/node_modules/async/lib/async.js:263:32
    at /Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/node_modules/async/lib/async.js:40:16
    at /Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/server/transforms.js:162:14
    at /Users/aaronjensen/Source/my-app/functions/node_modules/rollbar/src/server/parser.js:289:12
```

**Comment by brianr** [comment]
Thanks @aaronjensen - we're looking into this today.

**Comment by rokob** [comment]
`Object.create(null)` ugh; I have a solution, will fix

**Comment by aaronjensen** [comment]
Thanks for the quick turnaround! Would you mind dropping a note here on the next release so I can upgrade and remove my workaround? Thanks
