### ISSUE TITLE
Build failing in prod environment for Angular 4 build

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#504]
v2.3.0
Potentially something to do with AOT and this issue: https://github.com/rollbar/rollbar.js/issues/402 ?

Followed the Angular 2+ steps and it worked fine in dev, but in production it fails (in the Angular 4 build sense):

config:
```
// start configure rollbar
import * as Rollbar from 'rollbar';
import { RollbarErrorHandler } from './shared/services/RollbarErrorHandler';
const rollbarConfig = {
accessToken: 'REDACTED',
captureUncaught: true,
captureUnhandledRejections: true,
enabled: true,
environment: 'dev'
};
export function rollbarFactory() {
return new Rollbar(rollbarConfig);
}
//end rollbar config
```

ng build --prod

```
ERROR in Error: Internal error: unknown identifier null
at Object.importExpr$$1 [as importExpr] (.../node_modules/@angular/compiler/bundles/compiler.umd.js:24071:23)
at tokenExpr (.../node_modules/@angular/compiler/bundles/compiler.umd.js:18428:39)
at providerDef (.../node_modules/@angular/compiler/bundles/compiler.umd.js:18331:20)
at .../node_modules/@angular/compiler/bundles/compiler.umd.js:18548:77
at Array.map (<anonymous>)
at NgModuleCompiler.compile (.../node_modules/@angular/compiler/bundles/compiler.umd.js:18548:44)
at AotCompiler._compileModule (.../node_modules/@angular/compiler/bundles/compiler.umd.js:24004:32)
at .../node_modules/@angular/compiler/bundles/compiler.umd.js:23916:66
at Array.forEach (<anonymous>)
at AotCompiler._compileImplFile (.../node_modules/@angular/compiler/bundles/compiler.umd.js:23916:19)
at .../node_modules/@angular/compiler/bundles/compiler.umd.js:23829:87
at Array.map (<anonymous>)
at AotCompiler.emitAllImpls (.../node_modules/@angular/compiler/bundles/compiler.umd.js:23829:52)
at CodeGenerator.emit (.../node_modules/@angular/compiler-cli/src/codegen.js:42:46)
at .../node_modules/@angular/compiler-cli/src/codegen.js:33:61
at <anonymous>
```

internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/conversation/9596477468%3Fq=AOT&tag=0

**Comment by sivabudh** [comment]
@and-megan Sorry, I clicked on the link and this was all I saw:

![cloudapp annotation 2017-11-17 at 5 06 29 pm png](https://user-images.githubusercontent.com/618729/32941834-b54a84bc-cbb9-11e7-91f9-0a8d5c79d11b.png)

**Comment by and-megan** [comment]
Hi @sivabudh, it's an internal convo I linked for @rokob for debugging/extra info.

**Comment by mattmcardle** [comment]
Any progress on this? Encountering this issue with Angular 5

**Comment by rivkahstandig3636** [comment]
We'll have our SDK engineer investigate this.

**Comment by mattmcardle** [comment]
@rivkahstandig3636 re-implemented with the updated instructions on your JS documentation, seems to be working ok now. Thanks!

**Comment by sivabudh** [comment]
@mattmcardle So I can use Rollbar in my Angular 4/5 now?

**Comment by rokob** [comment]
Yes, things work via the instructions now

**Comment by afogel** [comment]
Hi!
I've got the exact same stack trace as @and-megan.
I'm on Angular 4.4.7 and rollbar 2.5.0.

Here's my `rollbarErrorHandler` module
```javascript
import { environment } from '../../environments/environment';
import { Injectable, ErrorHandler, InjectionToken, Inject } from '@angular/core';
import * as Rollbar from 'rollbar';

export const rollbarConfig = {
  accessToken: environment.rollbarClientToken,
  captureUncaught: true,
  captureUnhandledRejections: true,
  environment: environment.envName
};

export const RollbarService = new InjectionToken<Rollbar>('rollbar');

@Injectable()
export class RollbarErrorHandler implements ErrorHandler {
  constructor(@Inject(RollbarService) private rollbar: Rollbar) {}

  handleError(err:any) : void {
    this.rollbar.error(err.originalError || err);
  }
}

export function rollbarFactory() {
  return new Rollbar(rollbarConfig);
}
```

and my `app.module` file (shortened to only show relevant code):

```javascript
import {
  rollbarConfig,
  RollbarErrorHandler,
  rollbarFactory
} from './services/rollbarErrorHandler.service';
...
import * as Rollbar from 'rollbar';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    ...
  ],
  imports: [
    BrowserModule,
    ... //
  ],
  providers: [
    AuthService,
    ...
    { provide: ErrorHandler, useClass: RollbarErrorHandler },
    { provide: Rollbar, useFactory: rollbarFactory },
    ...
   ],
  entryComponents: [ModalComponent],
  bootstrap: [AppComponent]
})

export class AppModule { }
```
