### ISSUE TITLE
TypeError: Cannot set property '_rollbarContext' of undefined (Error)

### ISSUE THREAD

**Issue by verynear2** [rollbar/rollbar.js#610]
I'm getting many errors with this message. I’m working off the snippet for angular 2 and later, since I’m using Angular 5.2 on this project. 

This plunkr shows my configuration: https://embed.plnkr.co/ldJVK9/ 

I also see this in the output:
"TypeError: Cannot set property '_rollbarContext' of undefined\n at XMLHttpRequest.t._rollbar_wrapped.t._rollbar_wrapped (webpack-internal:///../../../../rollbar/dist/rollbar.umd.min.js:1:5655)\n at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425:31)\n at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4952:33)\n at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:424:36)\n at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192:47)\n at ZoneTask.invokeTask [as invoke] (webpack-internal:///../../../../zone.js/dist/zone.js:499:34)\n at invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:1540:14)\n at XMLHttpRequest.globalZoneAwareCallback (webpack-internal:///../../../../zone.js/dist/zone.js:1566:17)"

**Comment by ajtran** [comment]
We suspect it might be because of webpack strict mode. Can you send us your config file?
