### ISSUE TITLE
Ng build --aot failing in Angular 4

### ISSUE THREAD

**Issue by afogel** [rollbar/rollbar.js#688]
Hi!
I've got the exact same stack trace as @and-megan in #504.
I'm on Angular 4.4.7 and rollbar 2.5.0.
Occurs when I run `ng build --aot`.

Here's my rollbarErrorHandler module
```typescript
import { environment } from '../../environments/environment';
import { Injectable, ErrorHandler, InjectionToken, Inject } from '@angular/core';
import * as Rollbar from 'rollbar';

export const rollbarConfig = {
  accessToken: environment.rollbarClientToken,
  captureUncaught: true,
  captureUnhandledRejections: true,
  environment: environment.envName
};

export const RollbarService = new InjectionToken<Rollbar>('rollbar');

@Injectable()
export class RollbarErrorHandler implements ErrorHandler {
  constructor(@Inject(RollbarService) private rollbar: Rollbar) {}

  handleError(err:any) : void {
    this.rollbar.error(err.originalError || err);
  }
}

export function rollbarFactory() {
  return new Rollbar(rollbarConfig);
}
```
and my app.module file (shortened to only show relevant code):
```typescript
import {
  rollbarConfig,
  RollbarErrorHandler,
  rollbarFactory
} from './services/rollbarErrorHandler.service';
...
import * as Rollbar from 'rollbar';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    ...
  ],
  imports: [
    BrowserModule,
    ...
  ],
  providers: [
    AuthService,
    ...
    { provide: ErrorHandler, useClass: RollbarErrorHandler },
    { provide: Rollbar, useFactory: rollbarFactory },
    ...
   ],
  entryComponents: [ModalComponent],
  bootstrap: [AppComponent]
})

export class AppModule { }
```
Full stack trace:
```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/arielfogel/Development/cahlr/Angular-AskOski/src'
ERROR in Error: Internal error: unknown identifier null
    at Object.importExpr$$1 [as importExpr] (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:24071:23)
    at tokenExpr (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:18428:39)
    at providerDef (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:18331:20)
    at /Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:18548:77
    at Array.map (<anonymous>)
    at NgModuleCompiler.compile (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:18548:44)
    at AotCompiler._compileModule (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:24004:32)
    at /Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:23916:66
    at Array.forEach (<anonymous>)
    at AotCompiler._compileImplFile (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:23916:19)
    at /Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:23829:87
    at Array.map (<anonymous>)
    at AotCompiler.emitAllImpls (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler/bundles/compiler.umd.js:23829:52)
    at CodeGenerator.emit (/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler-cli/src/codegen.js:42:46)
    at /Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/@angular/compiler-cli/src/codegen.js:33:61
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by jessewgibbs** [comment]
@rokob could you take a look at this?

**Comment by rokob** [comment]
Is there any chance that switching
```
import * as Rollbar from 'rollbar';
```
to
```
import Rollbar from 'rollbar';
```
works?

**Comment by afogel** [comment]
alas, changing it to `import Rollbar from 'rollbar';` breaks my dev environment when I run `ng serve`:
```
ERROR in /Users/arielfogel/Development/cahlr/Angular-AskOski/src/app/services/rollbarErrorHandler.service.ts (3,8): Module '"/Users/arielfogel/Development/cahlr/Angular-AskOski/node_modules/rollbar/index"' has no default export.
```

**Comment by rokob** [comment]
Okay gotcha. I'll dig in to this, I remember an issue with AOT but thought it was resolved, guess not.

**Comment by afogel** [comment]
Thanks!

**Comment by rokob** [comment]
I just think the docs are off. I changed
```
{ provide: Rollbar, useFactory: rollbarFactory }
```
to
```
{ provide: RollbarService, useFactory: rollbarFactory }
```
and everything seems to be working for me. I had to update some imports and whatnot, but that is the basic change. Below are the full files that I ended up with in a new project that works with: `ng build`, `ng build --aot`, and `ng serve`.

`src/app/app.module.ts`
``` s/a/app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import {
  RollbarErrorHandler,
  RollbarService,
  rollbarFactory
} from './services/rollbarErrorHandler.service';

import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [
    { provide: ErrorHandler, useClass: RollbarErrorHandler },
    { provide: RollbarService, useFactory: rollbarFactory }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

`src/app/services/rollbarErrorHandler.service.ts`
```  s/a/s/rollbarErrorHandler.service.ts
import { environment } from '../../environments/environment';
import { Injectable, ErrorHandler, InjectionToken, Inject } from '@angular/core';
import * as Rollbar from 'rollbar';

export const rollbarConfig = {
  accessToken: environment.rollbarClientToken,
  captureUncaught: true,
  captureUnhandledRejections: true,
  environment: environment.envName
};

export const RollbarService = new InjectionToken<Rollbar>('rollbar');

@Injectable()
export class RollbarErrorHandler implements ErrorHandler {
  constructor(@Inject(RollbarService) private rollbar: Rollbar) {}

  handleError(err: any): void {
    this.rollbar.error(err.originalError || err);
  }
}

export function rollbarFactory() {
  return new Rollbar(rollbarConfig);
}
```

**Comment by jessewgibbs** [comment]
@rokob could you give https://github.com/rollbar/docs/blob/master/onboarding/angular2.md? A quick review?  Those are the onboarding instructions shown in-app.  It looks right to me, but I'm not that familiar w/ Angular.

**Comment by jessewgibbs** [comment]
@afogel this should be resolved now per Andrew's updates to our docs and last comment.  I'm going to close this issue, but if you continue to encounter issues, please let us know.
